pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/nukalavarshita/devops-nodejs-pipeline.git'
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                sh '''
                    export DOCKERHUB_USERNAME=varshitanukala
                    export DOCKERHUB_PASSWORD=Varshi@808

                    echo "Logging into DockerHub..."
                    echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

                    echo "Running build and push script..."
                    chmod +x scripts/build_and_push.sh
                    ./scripts/build_and_push.sh
                '''
            }
        }

        stage('Provision Infrastructure with Terraform') {
            steps {
                dir('infra') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Deploy App with Ansible') {
            steps {
                sh 'ansible-playbook -i ansible/hosts.ini ansible/deploy.yml'
            }
        }
    }

    post {
        success {
            echo '✅ Deployment pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed. Check the logs for details.'
        }
    }
}
